name: Build ClientMod DLL

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild clientmod.sln /p:Configuration=Release /p:Platform=x86 /p:WindowsTargetPlatformVersion=10.0

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: clientmod-dll
        path: '**/*.dll'
